"""empty message

Revision ID: 43547e9da2eb
Revises: d080c9104946
Create Date: 2016-12-27 16:53:55.451000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43547e9da2eb'
down_revision = 'd080c9104946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
