"""empty message

Revision ID: 5b7121a3308d
Revises: 
Create Date: 2017-01-13 12:02:09.874000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7121a3308d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('dataChunk1', sa.String(length=6000), nullable=True),
    sa.Column('dataChunk2', sa.String(length=6000), nullable=True),
    sa.Column('dataChunk3', sa.String(length=6000), nullable=True),
    sa.Column('dataChunk4', sa.String(length=6000), nullable=True),
    sa.Column('mouseDataChunk1', sa.String(length=8000), nullable=True),
    sa.Column('mouseDataChunk2', sa.String(length=8000), nullable=True),
    sa.Column('mouseDataChunk3', sa.String(length=8000), nullable=True),
    sa.Column('mouseDataChunk4', sa.String(length=8000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('datachunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=6000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datachunks')
    op.drop_table('users')
    op.drop_table('collect')
    # ### end Alembic commands ###
