"""empty message

Revision ID: 681d7fbccd68
Revises: 8e5d79bba9ac
Create Date: 2017-04-11 23:18:53.902256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681d7fbccd68'
down_revision = '8e5d79bba9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KeypressGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResearchUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keypressData',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('press_timestamp', sa.String(length=15), nullable=True),
    sa.Column('release_timestamp', sa.String(length=15), nullable=True),
    sa.Column('keycode', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['KeypressGroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ResearchUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('researchusers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchusers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('keypressData')
    op.drop_table('ResearchUser')
    op.drop_table('KeypressGroup')
    # ### end Alembic commands ###
