"""empty message

Revision ID: 8d6457d16137
Revises: 681d7fbccd68
Create Date: 2017-04-12 17:20:15.822655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6457d16137'
down_revision = '681d7fbccd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MouseMoveGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MouseMoveData',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=15), nullable=True),
    sa.Column('x', sa.String(length=4), nullable=True),
    sa.Column('y', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['MouseMoveGroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ResearchUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MouseMoveData')
    op.drop_table('MouseMoveGroup')
    # ### end Alembic commands ###
