"""empty message

Revision ID: 8e5d79bba9ac
Revises: 5b7121a3308d
Create Date: 2017-04-11 22:43:00.235085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5d79bba9ac'
down_revision = '5b7121a3308d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researchusers')
    # ### end Alembic commands ###
